# Generated by Django 5.1.4 on 2025-01-01 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_pessoa_ativo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoa',
            options={'ordering': ['nome', 'ativo']},
        ),
    ]
