# Generated by Django 5.1.4 on 2025-01-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0003_alter_pessoa_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='nascimento',
            field=models.DateField(null=True, verbose_name='nascimento'),
        ),
    ]
