# Generated by Django 4.2.18 on 2025-01-26 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_exame_procedimento_alter_pessoa_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoa',
            options={},
        ),
    ]
