# Generated by Django 4.2.18 on 2025-01-29 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia_analise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Grupo')),
                ('Idade', models.FloatField(blank=True, null=True, verbose_name='Idade')),
                ('Sexo', models.FloatField(blank=True, null=True, verbose_name='Sexo')),
                ('Sangue_A_neg', models.FloatField(blank=True, null=True, verbose_name='Sangue_A_neg')),
                ('Sangue_AB_pos', models.FloatField(blank=True, null=True, verbose_name='Sangue_AB_pos')),
                ('Sangue_AB_neg', models.FloatField(blank=True, null=True, verbose_name='Sangue_AB_neg')),
                ('Sangue_B_pos', models.FloatField(blank=True, null=True, verbose_name='Sangue_B_pos')),
                ('Sangue_B_neg', models.FloatField(blank=True, null=True, verbose_name='Sangue_B_neg')),
                ('Sangue_O_pos', models.FloatField(blank=True, null=True, verbose_name='Sangue_O_pos')),
                ('Sangue_O_neg', models.FloatField(blank=True, null=True, verbose_name='Sangue_O_neg')),
                ('Cond_Cancer', models.FloatField(blank=True, null=True, verbose_name='Cond_Cancer')),
                ('Cond_Diabetes', models.FloatField(blank=True, null=True, verbose_name='Cond_Diabetes')),
                ('Cond_Hipertensao', models.FloatField(blank=True, null=True, verbose_name='Cond_Hipertensao')),
                ('Cond_Obesidade', models.FloatField(blank=True, null=True, verbose_name='Cond_Obesidade')),
                ('Adm_Emerg', models.FloatField(blank=True, null=True, verbose_name='Adm_Emerge')),
                ('Adm_Urgente', models.FloatField(blank=True, null=True, verbose_name='Adm_Urgente')),
                ('Med_Ibuprof', models.FloatField(blank=True, null=True, verbose_name='Med_Ibuprof')),
                ('Med_Lipitor', models.FloatField(blank=True, null=True, verbose_name='Med_Lipitor')),
                ('Med_Parac', models.FloatField(blank=True, null=True, verbose_name='Med_Parac')),
                ('Med_Penici', models.FloatField(blank=True, null=True, verbose_name='Med_Penici')),
                ('Teste_Inconclus', models.FloatField(blank=True, null=True, verbose_name='Teste_Inconclus')),
                ('Teste_Normal', models.FloatField(blank=True, null=True, verbose_name='Teste_Normal')),
                ('Teste_Anormal', models.FloatField(blank=True, null=True, verbose_name='Teste_Anormal')),
            ],
        ),
        migrations.AlterModelOptions(
            name='dados',
            options={},
        ),
    ]
