# Generated by Django 4.2.17 on 2025-01-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia_analise', '0002_pacientes_alter_dados_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacientes',
            name='Adm_Emerg',
        ),
        migrations.RemoveField(
            model_name='pacientes',
            name='Med_Ibuprof',
        ),
        migrations.RemoveField(
            model_name='pacientes',
            name='Med_Parac',
        ),
        migrations.RemoveField(
            model_name='pacientes',
            name='Med_Penici',
        ),
        migrations.RemoveField(
            model_name='pacientes',
            name='Sangue_AB_neg',
        ),
        migrations.RemoveField(
            model_name='pacientes',
            name='Sangue_AB_pos',
        ),
        migrations.RemoveField(
            model_name='pacientes',
            name='Sangue_A_neg',
        ),
        migrations.RemoveField(
            model_name='pacientes',
            name='Sangue_B_neg',
        ),
        migrations.RemoveField(
            model_name='pacientes',
            name='Sangue_B_pos',
        ),
        migrations.RemoveField(
            model_name='pacientes',
            name='Sangue_O_neg',
        ),
        migrations.RemoveField(
            model_name='pacientes',
            name='Sangue_O_pos',
        ),
        migrations.RemoveField(
            model_name='pacientes',
            name='Teste_Inconclus',
        ),
        migrations.AddField(
            model_name='pacientes',
            name='Adm_Emergencia',
            field=models.FloatField(blank=True, null=True, verbose_name='Adm_Emergencia'),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='Med_Ibuprofeno',
            field=models.FloatField(blank=True, null=True, verbose_name='Med_Ibuprofeno'),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='Med_Paracetamol',
            field=models.FloatField(blank=True, null=True, verbose_name='Med_Paracetamol'),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='Med_Penicilina',
            field=models.FloatField(blank=True, null=True, verbose_name='Med_Penicilina'),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='Teste_Inconclusivo',
            field=models.FloatField(blank=True, null=True, verbose_name='Teste_Inconclusivo'),
        ),
    ]
