# Generated by Django 4.2.17 on 2025-01-30 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ia_analise', '0003_remove_pacientes_adm_emerg_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacientes',
            old_name='Adm_Urgente',
            new_name='Adm_Urgencia',
        ),
    ]
