# Generated by Django 4.2.19 on 2025-02-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia_analise', '0006_datasetcancerbucal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasetcancerbucal',
            name='infeccao_por_hpv',
        ),
        migrations.RemoveField(
            model_name='datasetcancerbucal',
            name='uso_de_protese_inadequada',
        ),
        migrations.AddField(
            model_name='datasetcancerbucal',
            name='infeccao_hpv',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='infeccao_hpv'),
        ),
        migrations.AddField(
            model_name='datasetcancerbucal',
            name='uso_protese_inadequada',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='uso_protese_inadequada'),
        ),
        migrations.AlterField(
            model_name='datasetcancerbucal',
            name='consumo_alcool',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='consumo_alcool'),
        ),
        migrations.AlterField(
            model_name='datasetcancerbucal',
            name='dieta_inadequada',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='dieta_inadequada'),
        ),
        migrations.AlterField(
            model_name='datasetcancerbucal',
            name='exposicao_solar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='exposicao_solar'),
        ),
        migrations.AlterField(
            model_name='datasetcancerbucal',
            name='grau_risco',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='grau_risco'),
        ),
        migrations.AlterField(
            model_name='datasetcancerbucal',
            name='grupo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='grupo'),
        ),
        migrations.AlterField(
            model_name='datasetcancerbucal',
            name='higiene_bucal_inadequada',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='higiene_bucal_inadequada'),
        ),
        migrations.AlterField(
            model_name='datasetcancerbucal',
            name='idade',
            field=models.FloatField(blank=True, null=True, verbose_name='idade'),
        ),
        migrations.AlterField(
            model_name='datasetcancerbucal',
            name='sexo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='sexo'),
        ),
        migrations.AlterField(
            model_name='datasetcancerbucal',
            name='tabagismo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='tabagismo'),
        ),
    ]
