# Generated by Django 4.2.19 on 2025-02-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia_analise', '0007_remove_datasetcancerbucal_infeccao_por_hpv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetcancerbucal',
            name='consumo_alcool',
            field=models.BooleanField(default=False),
        ),
    ]
